export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const CLEAR_TOKEN = 'CLEAR_TOKEN'

export const GET_EVENT_FAILURE = 'GET_EVENT_FAILURE'
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS'
export const GET_EVENT_START = 'GET_EVENT_START'

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'
export const GET_USER_START = 'GET_USER_START'

export const GET_VIEW_SUCCESS = 'GET_VIEW_SUCCESS'
export const GET_VIEW_FAILURE = 'GET_VIEW_FAILURE'
export const GET_VIEW_START = 'GET_VIEW_START'

export const GET_VIEWEVENT_SUCCESS = 'GET_VIEWEVENT_SUCCESS'
export const GET_VIEWEVENT_FAILURE = 'GET_VIEWEVENT_FAILURE'
export const GET_VIEWEVENT_START = 'GET_VIEWEVENT_START'

export const ASSIGN_TODOITEM_SUCCESS = 'ASSIGN_TODOITEM_SUCCESS'
export const ASSIGN_TODOITEM_FAILURE = 'ASSIGN_TODOITEM_FAILURE'
export const ASSIGN_TODOITEM_START = 'ASSIGN_TODOITEM_START'
export const ASSIGN_TODOITEM = 'ASSIGN_TODOITEM'

export const COMPLETE_TODOITEM = 'COMPLETE_TODOITEM'

export const JOIN_EVENT = 'JOIN_EVENT'

export const LEFT_EVENT = 'LEFT_EVENT'
